FROM oven/bun:latest AS builder
WORKDIR /usr/src/app
COPY . .
RUN bun build src/server.ts --target node --outdir ./dist

FROM node:alpine AS runner
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/package.json .
COPY --from=builder /usr/src/app/node_modules .
COPY --from=builder /usr/src/app/dist/server.js ./index.mjs
COPY prisma .
RUN npm install --frozen-lockfile
RUN npx prisma generate
EXPOSE 50051/tcp
ENTRYPOINT [ "node", "index.mjs" ]

